default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: breed

test:
  <<: *default
  database: breed-test

production: &production
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>